version: '3.8'

services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./laravel-bbs-app:/var/www/laravel-bbs-app
    working_dir: /var/www/laravel-bbs-app
    depends_on:
      - db
    networks:
      - laravel-network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: db-user        # dbサービスのMYSQL_USERと一致させる
      PMA_PASSWORD: db-pass    # dbサービスのMYSQL_PASSWORDと一致させる
    ports:
      - "8080:80"
    networks:
      - laravel-network

networks:
  laravel-network: